pin "application"
pin "bootstrap", to: "https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
pin "trix"
 #pin "@rails/actiontext", to: "actiontext.esm.js"
 pin "@rails/actiontext", to: "https://cdn.jsdelivr.net/npm/@rails/actiontext@7.0.8/actiontext.esm.js"
pin "trix"
pin "@rails/actiontext", to: "actiontext.esm.js"
